USE [TermoAceite]
GO

INSERT INTO [dbo].[Unidade]
           ([nome]
           ,[descricao])
     VALUES
           (' PA-ARCOVERDE/ADMINISTRA��O ', 'Unidade do SENAC'),
('ASSESSORIA DA PRESID�NCIA ', 'Unidade do SENAC'),
('AT/ESTUDOS E PESQUISAS ', 'Unidade do SENAC'),
('AT/GER�NCIA ', 'Unidade do SENAC'),
('AT/PLANEJAMENTO E OR�AMENTO ', 'Unidade do SENAC'),
('CAS - CENTRAL DE ATENDIMENTO ', 'Unidade do SENAC'),
('CAS - CENTRAL TELEF�NICA ', 'Unidade do SENAC'),
('CECON - CARUARU ', 'Unidade do SENAC'),
('CENTRO IDIOMAS/CURSOS ', 'Unidade do SENAC'),
('CENTRO IDIOMAS/GER�NCIA ', 'Unidade do SENAC'),
('CEP MEDIOTEC - COORDENA��O ', 'Unidade do SENAC'),
('CEP MEDIOTEC - SALA DE AULA ', 'Unidade do SENAC'),
('CETII ', 'Unidade do SENAC'),
('CHT/EVENTOS ', 'Unidade do SENAC'),
('CHT/GER�NCIA ', 'Unidade do SENAC'),
('CHT/HOSPITALIDADE ', 'Unidade do SENAC'),
('CHT/LANCHONETE ESCOLA ', 'Unidade do SENAC'),
('CHT/MANUTEN��O ', 'Unidade do SENAC'),
('CHT/PROJETO ', 'Unidade do SENAC'),
('CHT/RESTAURANTE ESCOLA ', 'Unidade do SENAC'),
('CHT/TURISMO ', 'Unidade do SENAC'),
('CMB/EMPRESA PEDAGOGICA ', 'Unidade do SENAC'),
('CMB/GER�NCIA ', 'Unidade do SENAC'),
('CMB/IMAGEM PESSOAL ', 'Unidade do SENAC'),
('CMB/MANUTEN��O ', 'Unidade do SENAC'),
('CMB/PROJETO ', 'Unidade do SENAC'),
('CMB/SA�DE ', 'Unidade do SENAC'),
('CONSELHO REGIONAL ', 'Unidade do SENAC'),
('CONTROLADORIA ', 'Unidade do SENAC'),
('CPL - COMISSAO PERMANENTE DE LICITA��O ', 'Unidade do SENAC'),
('CTV/CURSOS ', 'Unidade do SENAC'),
('CTV/GER�NCIA ', 'Unidade do SENAC'),
('DAF - CONTRATOS E DOCUMENTOS ', 'Unidade do SENAC'),
('DAF - CONTROLADORIA ', 'Unidade do SENAC'),
('DAF - COORDENA��O DE CONTRATOS E DOCUMENTOS ', 'Unidade do SENAC'),
('DAF - DIRETORIA ADMINISTRA��O E FINAN�AS ', 'Unidade do SENAC'),
('DAF - SECRETARIA ADMINISTRATIVA ', 'Unidade do SENAC'),
('DAF/SECRETARIA ADMINISTRATIVA ', 'Unidade do SENAC'),
('DEP ', 'Unidade do SENAC'),
('DEP - BIBLIOTECA ', 'Unidade do SENAC'),
('DEP - COORDENA��O SENAC M�VEL ', 'Unidade do SENAC'),
('DEP - CPED/DESENVOLVIMENTO PEDAGOGICO ', 'Unidade do SENAC'),
('DEP - CPED/EQUIPE TECNICA ', 'Unidade do SENAC'),
('DEP - CPED/RECURSOS DIDATICOS ', 'Unidade do SENAC'),
('DEP - CPROD/EQUIPE TECNICA (PROJETOS) ', 'Unidade do SENAC'),
('DEP - DIRETORIA DE EDUCA��O PROFISSIONAL ', 'Unidade do SENAC'),
('DEP - EAD/EDUCA��O A DIST�NCIA ', 'Unidade do SENAC'),
('DEP - GER�NCIA DE DESENVOLVIMENTO DE PRODUTO ', 'Unidade do SENAC'),
('DEP - GER�NCIA DE DESENVOLVIMENTO EDUCACIONAL ', 'Unidade do SENAC'),
('DEP - GER�NCIA DE PROCESSOS EDUCACIONAIS ', 'Unidade do SENAC'),
('DEP - NUCLEO DE EDUCA��O A DIST�NCIA ', 'Unidade do SENAC'),
('DEP - NUCLEO DE PROGRAMAS EDUCACIONAIS ', 'Unidade do SENAC'),
('DEP - SECRETARIA EDUCACIONAL ', 'Unidade do SENAC'),
('DEP/BIBLIOTECA/ESPA�O CULTURAL ', 'Unidade do SENAC'),
('DEP/CONV�NIO-PROMATA ', 'Unidade do SENAC'),
('DEP/RECURSOS INSTRUCIONAIS ', 'Unidade do SENAC'),
('DEP/SECRETARIA/EQUIPE T�CNICA ', 'Unidade do SENAC'),
('DIOP - COORDENA��O CAS ', 'Unidade do SENAC'),
('DIOP - COORDENA��O DE PROGRAMAS ', 'Unidade do SENAC'),
('DIOP - DIRETORIA DE OPERA��ES ', 'Unidade do SENAC'),
('DIOP - GER�NCIA REGIONAL AGRESTE  ', 'Unidade do SENAC'),
('DIOP - GER�NCIA REGIONAL COMERCIAL ', 'Unidade do SENAC'),
('DIOP - GERENCIA REGIONAL MATA NORTE ', 'Unidade do SENAC'),
('DIOP - GER�NCIA REGIONAL MATA SUL ', 'Unidade do SENAC'),
('DIOP - GER�NCIA REGIONAL SERT�O ', 'Unidade do SENAC'),
('DIOP - SENAC MOVEL ', 'Unidade do SENAC'),
('DIOP - SM/COMERCIO ', 'Unidade do SENAC'),
('DIOP - SM/GEST�O ', 'Unidade do SENAC'),
('DIOP - SM/IMAGEM PESSOAL ', 'Unidade do SENAC'),
('DIOP - SM/INFORM�TICA ', 'Unidade do SENAC'),
('DIOP - SM/TURISMO / HOSPITALIDADE ', 'Unidade do SENAC'),
('DIRE��O REGIONAL ', 'Unidade do SENAC'),
('DIRETORIA DE ADMINISTRA��O E FINAN�AS ', 'Unidade do SENAC'),
('DIRETORIA DE OPERA��ES ', 'Unidade do SENAC'),
('DPE - COORDENA��O DO NUCELO DE PROJETOS ESTRAT�GICOS ', 'Unidade do SENAC'),
('DPE - COORDENA��O DO N�CLEO DE RELACIONAMENTOS E PARCERIAS ', 'Unidade do SENAC'),
('DPE - DIRETORIA DE PROJETOS ESTRAT�GICOS ', 'Unidade do SENAC'),
('DPE - GER�NCIA DE NOVOS NEGOCIOS ', 'Unidade do SENAC'),
('DR/CENTRO PROCESSAMENTO DADOS ', 'Unidade do SENAC'),
('DR/COMISSAO PERMANENTE LICITACAO ', 'Unidade do SENAC'),
('DR/SE��O COMUNIC E MARKETING - SECOM ', 'Unidade do SENAC'),
('FAC-GER�NCIA ACAD�MICA DE EDUCA��O SUPERIOR ', 'Unidade do SENAC'),
('FAC-SENAC/ADMINISTRA��O ', 'Unidade do SENAC'),
('FAC-SENAC/ADMINISTRA��O/COM. EXTERIOR ', 'Unidade do SENAC'),
('FAC-SENAC/CARUARU ', 'Unidade do SENAC'),
('FAC-SENAC/DESIGN ', 'Unidade do SENAC'),
('FAC-SENAC/EXTENS�O EDUCACIONAL ', 'Unidade do SENAC'),
('FAC-SENAC/GER�NCIA DE OPERA��ES ADM ', 'Unidade do SENAC'),
('FAC-SENAC/GRADUA��O GEST�O ', 'Unidade do SENAC'),
('FAC-SENAC/GRADUA��O INFORMATICA ', 'Unidade do SENAC'),
('FAC-SENAC/GRADUA��O SA�DE ', 'Unidade do SENAC'),
('FAC-SENAC/PETROLINA ', 'Unidade do SENAC'),
('FAC-SENAC/POS-EAD ', 'Unidade do SENAC'),
('FAC-SENAC/TECNOLOGIA DESIGN DE MODA ', 'Unidade do SENAC'),
('FAC-SENAC/TECNOLOGIA EM EVENTOS ', 'Unidade do SENAC'),
('FAC-SENAC/TURISMO HOSP./GASTRONOMIA ', 'Unidade do SENAC'),
('GAO - GER�NCIA DE ARQUITETURA E OBRAS ', 'Unidade do SENAC'),
('GCF - CONTABILIDADE ', 'Unidade do SENAC'),
('GCF - COORDENA��O CONTABIL ', 'Unidade do SENAC'),
('GCF - COORDENA��O FINANCEIRA ', 'Unidade do SENAC'),
('GCF - FINANC/CONTAS A PAGAR ', 'Unidade do SENAC'),
('GCF - FINANC/CONTAS A RECEBER ', 'Unidade do SENAC'),
('GCF - FINANC/TESOURARIA ', 'Unidade do SENAC'),
('GCF - GER�NCIA DE CONTABILIDADE E FINAN�AS ', 'Unidade do SENAC'),
('GEA - COORDENA��O DE ENGENHARIA ', 'Unidade do SENAC'),
('GEA - GER�NCIA DE ENGENHARIA E ARQUITETURA ', 'Unidade do SENAC'),
('GERCOM - CENTRAL DE OPORTUNIDADES DO EGRESSO ', 'Unidade do SENAC'),
('GERCOM - COORDENA��O DE RELACIONAMENTO ', 'Unidade do SENAC'),
('GERCOM - COORDENA��O DE RELACIONAMENTO SENAC ', 'Unidade do SENAC'),
('GERCOM - EVENTOS ', 'Unidade do SENAC'),
('GERCOM - GR�FICA ', 'Unidade do SENAC'),
('GERCOM - IMPRENSA ', 'Unidade do SENAC'),
('GERCOM - RELACIONAMENTO E COMUNICA��O ', 'Unidade do SENAC'),
('GER�NCIA COMERCIAL ', 'Unidade do SENAC'),
('GER�NCIA DE PLANEJAMENTO E GEST�O ', 'Unidade do SENAC'),
('GER�NCIA DE RELACIONAMENTO E COMUNICA��O ', 'Unidade do SENAC'),
('GERES ', 'Unidade do SENAC'),
('GLC - COORDENA��O DE COMPRAS ', 'Unidade do SENAC'),
('GLC - COORDENA��O DE CONTRATOS ', 'Unidade do SENAC'),
('GLC - COORDENA��O DE LICITA��O ', 'Unidade do SENAC'),
('GLC - GER�NCIA DE LICITA��O E COMPRAS ', 'Unidade do SENAC'),
('GNC - COORDENA��O DE CONTROLADORIA ', 'Unidade do SENAC'),
('GNC - COORDENA��O DE OUVIDORIA ', 'Unidade do SENAC'),
('GNC - GER�NCIA DE NUCLEO DE COMPLIANCE ', 'Unidade do SENAC'),
('GPC - COORDENA��O DE ADMINISTRA��O DE PESSOAL ', 'Unidade do SENAC'),
('GPC - COORDENA��O DE DESENVOLVIMENTO PESSOAL ', 'Unidade do SENAC'),
('GPC - GER�NCIA DE PESSOAS E CULTURA ', 'Unidade do SENAC'),
('GPC - MEDICINA E SEGURAN�A DO TRABALHO ', 'Unidade do SENAC'),
('GPG - OR�AMENTO ', 'Unidade do SENAC'),
('GPG - PESQUISA ', 'Unidade do SENAC'),
('GPG - PLANEJAMENTO E GEST�O ', 'Unidade do SENAC'),
('GPG - PLANEJAMENTO E PESQUISA ', 'Unidade do SENAC'),
('GRH ', 'Unidade do SENAC'),
('GRH - ADMINISTRA��O DE PESSOAL ', 'Unidade do SENAC'),
('GRH - COORDENA��O DE ADMINISTRA��O DE PESSOAL ', 'Unidade do SENAC'),
('GRH - DESENVOLVIMENTO ', 'Unidade do SENAC'),
('GRH - GER�NCIA DE RELA��ES HUMANAS ', 'Unidade do SENAC'),
('GRH - MEDICINA E SEGURAN�A DO TRABALHO ', 'Unidade do SENAC'),
('GRH - RECRUTAMENTO E SELE��O ', 'Unidade do SENAC'),
('GRH/SE��O DE PESSOAL ', 'Unidade do SENAC'),
('GRH/SE��O DESENVOLVIMENTO PESSOAL ', 'Unidade do SENAC'),
('GRH/SETOR DE SMT ', 'Unidade do SENAC'),
('GSG/SE��O DE MATERIAL ', 'Unidade do SENAC'),
('GSG/SPMC ', 'Unidade do SENAC'),
('GSG/SPMC/EL�TRICA ', 'Unidade do SENAC'),
('GSG/SPMC/HIDR�ULICA ', 'Unidade do SENAC'),
('GSG/SPMC/REFRIGERA��O ', 'Unidade do SENAC'),
('GSG/SPMC/SERVI�OS ADMINISTRATIVOS ', 'Unidade do SENAC'),
('GSG/SPMC/SERVI�OS DE PRODU��O ', 'Unidade do SENAC'),
('GSI - ALMOXARIFADO ', 'Unidade do SENAC'),
('GSI - ARQUITETURA E OBRAS ', 'Unidade do SENAC'),
('GSI - COMPRAS ', 'Unidade do SENAC'),
('GSI - COORDENA��O DE COMPRAS ', 'Unidade do SENAC'),
('GSI - COORDENA��O DE ENGENHARIA ', 'Unidade do SENAC'),
('GSI - COORDENA��O DE PATRIMONIO ', 'Unidade do SENAC'),
('GSI - COORDENA��O DE SERVI�OS ', 'Unidade do SENAC'),
('GSI - GER�NCIA DE SERVI�OS E INFRAESTRUTURA ', 'Unidade do SENAC'),
('GSI - MANUTEN��O E TRANSPORTES ', 'Unidade do SENAC'),
('GSI - PATRIM�NIO ', 'Unidade do SENAC'),
('GSI - SERVI�OS ', 'Unidade do SENAC'),
('GSI - SERVI�OS/LIMPEZA ', 'Unidade do SENAC'),
('GSI - SERVI�OS/PORTARIA ', 'Unidade do SENAC'),
('GSI - SERVI�OS/TRANSPORTE ', 'Unidade do SENAC'),
('GST - COORDENA��O DE SERVI�OS ', 'Unidade do SENAC'),
('GST - GER�NCIA DE SERVI�OS E TRANSPORTE ', 'Unidade do SENAC'),
('GST - SERVI�OS/LIMPEZA ', 'Unidade do SENAC'),
('GST - SERVI�OS/PORTARIA ', 'Unidade do SENAC'),
('GST - SERVI�OS/TRANSPORTE ', 'Unidade do SENAC'),
('GTI - GER�NCIA TECNOLOGIA DA INFORMA��O ', 'Unidade do SENAC'),
('GTI - INFRAESTRUTURA E SUPORTE ', 'Unidade do SENAC'),
('GTI - SISTEMAS ', 'Unidade do SENAC'),
('LANCHONETE ESCOLA ', 'Unidade do SENAC'),
('MEDIOTEC/CARUARU ', 'Unidade do SENAC'),
('MEDIOTEC/PAULISTA ', 'Unidade do SENAC'),
('NINF/CURSOS ', 'Unidade do SENAC'),
('NINF/GER�NCIA ', 'Unidade do SENAC'),
('NINF/PROJETO ', 'Unidade do SENAC'),
('OUVIDORIA ', 'Unidade do SENAC'),
('PA-ARCOVERDE/ARTES ', 'Unidade do SENAC'),
('PA-ARCOVERDE/BELEZA ', 'Unidade do SENAC'),
('PA-ARCOVERDE/CAPACITA��O EDUCACIONAL ', 'Unidade do SENAC'),
('PA-ARCOVERDE/COMERCIO ', 'Unidade do SENAC'),
('PA-ARCOVERDE/COMUNICA��O ', 'Unidade do SENAC'),
('PA-ARCOVERDE/GEST�O ', 'Unidade do SENAC'),
('PA-ARCOVERDE/HOSPITALIDADE ', 'Unidade do SENAC'),
('PA-ARCOVERDE/INFORM�TICA ', 'Unidade do SENAC'),
('PA-ARCOVERDE/LAZER ', 'Unidade do SENAC'),
('PA-ARCOVERDE/MEIO AMBIENTE ', 'Unidade do SENAC'),
('PA-ARCOVERDE/MODA ', 'Unidade do SENAC'),
('PA-ARCOVERDE/SA�DE ', 'Unidade do SENAC'),
('PA-ARCOVERDE/TURISMO ', 'Unidade do SENAC'),
('PA-BRASILAR/ADMINISTRA��O ', 'Unidade do SENAC'),
('PA-BRASILAR/COM�RCIO ', 'Unidade do SENAC'),
('PA-BRASILAR/CONSERVA��O E ZELADORIA ', 'Unidade do SENAC'),
('PA-BRASILAR/GEST�O ', 'Unidade do SENAC'),
('PA-BRASILAR/SA�DE ', 'Unidade do SENAC'),
('PA-CABO/ADMINISTRA��O ', 'Unidade do SENAC'),
('PA-CABO/ARTES ', 'Unidade do SENAC'),
('PA-CABO/BELEZA ', 'Unidade do SENAC'),
('PA-CABO/COMERCIO ', 'Unidade do SENAC'),
('PA-CABO/GEST�O ', 'Unidade do SENAC'),
('PA-CABO/HOSPITALIDADE ', 'Unidade do SENAC'),
('PA-CABO/IDIOMAS ', 'Unidade do SENAC'),
('PA-CABO/INFORM�TICA ', 'Unidade do SENAC'),
('PA-CABO/MODA ', 'Unidade do SENAC'),
('PA-CABO/SA�DE ', 'Unidade do SENAC'),
('PA-MATA NORTE/ADMINISTRA��O ', 'Unidade do SENAC'),
('PA-MATA NORTE/CURSOS ', 'Unidade do SENAC'),
('PA-PAIVA/ADMINISTRA��O ', 'Unidade do SENAC'),
('PA-PAIVA/GEST�O ', 'Unidade do SENAC'),
('PA-PAIVA/HOSPITALIDADE ', 'Unidade do SENAC'),
('PA-PAIVA/IDIOMAS ', 'Unidade do SENAC'),
('PA-PAIVA/INFORM�TICA ', 'Unidade do SENAC'),
('PA-PAIVA/SA�DE ', 'Unidade do SENAC'),
('PA-PAIVA/TURISMO ', 'Unidade do SENAC'),
('PA-SALGUEIRO/ADMINISTRA��O ', 'Unidade do SENAC'),
('PA-SALGUEIRO/BELEZA ', 'Unidade do SENAC'),
('PA-SALGUEIRO/COMERCIO ', 'Unidade do SENAC'),
('PA-SALGUEIRO/EDUCACIONAL ', 'Unidade do SENAC'),
('PA-SALGUEIRO/GEST�O ', 'Unidade do SENAC'),
('PA-SALGUEIRO/HOSPITALIDADE ', 'Unidade do SENAC'),
('PA-SALGUEIRO/INFORM�TICA ', 'Unidade do SENAC'),
('PA-SALGUEIRO/SA�DE ', 'Unidade do SENAC'),
('PA-SALGUEIRO/TURISMO ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/ADMINISTRA��O ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/ARTES ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/BELEZA ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/COM�RCIO ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/CONSERVA��O E ZELADORIA ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/EDUCACIONAL ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/GEST�O ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/HOSPITALIDADE ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/IDIOMAS ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/INFORM�TICA ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/LAZER ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/MODA ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/PRODU��O ALIMENT�CIA ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/SA�DE ', 'Unidade do SENAC'),
('PA-SERRA TALHADA/TURISMO ', 'Unidade do SENAC'),
('REGIONAL AGRESTE/CURSOS ', 'Unidade do SENAC'),
('RESTAURANTE ESCOLA ', 'Unidade do SENAC'),
('SAL�O EMPRESA PEDAGOGICA ', 'Unidade do SENAC'),
('SENAC - CECON/GER�NCIA ', 'Unidade do SENAC'),
('SENAC M�VEL/SA�DE ', 'Unidade do SENAC'),
('SENAC-UIP/BELEZA ', 'Unidade do SENAC'),
('SENAC-UIP/EMPRESA PEDAGOGICA ', 'Unidade do SENAC'),
('SENAC-UIP/GER�NCIA  ', 'Unidade do SENAC'),
('SENAC-UIP/MODA ', 'Unidade do SENAC'),
('SENAC-UIP/SA�DE ', 'Unidade do SENAC'),
('SENAC-UTIC/CURSOS ', 'Unidade do SENAC'),
('SENAC-UTIC/GER�NCIA ', 'Unidade do SENAC'),
('SENAC-UTV/GER�NCIA ', 'Unidade do SENAC'),
('SENAC-UTV/GEST�O ', 'Unidade do SENAC'),
('SM/COM�RCIO ', 'Unidade do SENAC'),
('SM/ESTA��O-FUTURO ', 'Unidade do SENAC'),
('SM/GER�NCIA ', 'Unidade do SENAC'),
('SM/GEST�O ', 'Unidade do SENAC'),
('SM/IMAGEM PESSOAL ', 'Unidade do SENAC'),
('SM/INFORM�TICA ', 'Unidade do SENAC'),
('SM/N.Sra DO CARMO ', 'Unidade do SENAC'),
('SM/PROJETO ', 'Unidade do SENAC'),
('SM/SA�DE ', 'Unidade do SENAC'),
('SM/TURISMO/HOSPITALIDADE ', 'Unidade do SENAC'),
('UEAD/ATIVIDADES CORRELATAS ', 'Unidade do SENAC'),
('UEAD/CONVENIO-PROCENTRO ', 'Unidade do SENAC'),
('UEAD/GER�NCIA ', 'Unidade do SENAC'),
('UEAD/GEST�O ', 'Unidade do SENAC'),
('UEAD/INFORM�TICA ', 'Unidade do SENAC'),
('UEAD/MEIO AMBIENTE ', 'Unidade do SENAC'),
('UEAD/TEC. EDUCACIONAL-ARPE ', 'Unidade do SENAC'),
('UEP - CARUARU/ARTES ', 'Unidade do SENAC'),
('UEP - CARUARU/ATIVID.CORRELATAS ', 'Unidade do SENAC'),
('UEP - CARUARU/COM�RCIO ', 'Unidade do SENAC'),
('UEP - CARUARU/GER�NCIA ', 'Unidade do SENAC'),
('UEP - CARUARU/GEST�O ', 'Unidade do SENAC'),
('UEP - CARUARU/IDIOMAS ', 'Unidade do SENAC'),
('UEP - CARUARU/IMAGEM PESSOAL ', 'Unidade do SENAC'),
('UEP - CARUARU/INFORM�TICA ', 'Unidade do SENAC'),
('UEP - CARUARU/MEDIOTEC ', 'Unidade do SENAC'),
('UEP - CARUARU/MODA ', 'Unidade do SENAC'),
('UEP - CARUARU/SA�DE ', 'Unidade do SENAC'),
('UEP - CARUARU/TUR.HOSPITALIDADE ', 'Unidade do SENAC'),
('UEP - GARANHUNS/ARTES ', 'Unidade do SENAC'),
('UEP - GARANHUNS/BELEZA ', 'Unidade do SENAC'),
('UEP - GARANHUNS/COM�RCIO ', 'Unidade do SENAC'),
('UEP - GARANHUNS/GER�NCIA ', 'Unidade do SENAC'),
('UEP - GARANHUNS/GEST�O ', 'Unidade do SENAC'),
('UEP - GARANHUNS/IDIOMAS ', 'Unidade do SENAC'),
('UEP - GARANHUNS/IMAGEM PESSOAL ', 'Unidade do SENAC'),
('UEP - GARANHUNS/INFORM�TICA ', 'Unidade do SENAC'),
('UEP - GARANHUNS/MODA ', 'Unidade do SENAC'),
('UEP - GARANHUNS/POSTO-ESCOLA ', 'Unidade do SENAC'),
('UEP - GARANHUNS/SA�DE ', 'Unidade do SENAC'),
('UEP - GARANHUNS/TUR.HOSPITALIDADE ', 'Unidade do SENAC'),
('UEP - PAULISTA/ARTES ', 'Unidade do SENAC'),
('UEP - PAULISTA/BELEZA ', 'Unidade do SENAC'),
('UEP - PAULISTA/COM�RCIO ', 'Unidade do SENAC'),
('UEP - PAULISTA/GER�NCIA ', 'Unidade do SENAC'),
('UEP - PAULISTA/GEST�O ', 'Unidade do SENAC'),
('UEP - PAULISTA/IDIOMAS ', 'Unidade do SENAC'),
('UEP - PAULISTA/IMAGEM PESSOAL ', 'Unidade do SENAC'),
('UEP - PAULISTA/INFORM�TICA ', 'Unidade do SENAC'),
('UEP - PAULISTA/MEDIOTEC ', 'Unidade do SENAC'),
('UEP - PAULISTA/MEIO AMBIENTE ', 'Unidade do SENAC'),
('UEP - PAULISTA/PRODU��O ALIMENT�CIA ', 'Unidade do SENAC'),
('UEP - PAULISTA/PROJETO ', 'Unidade do SENAC'),
('UEP - PAULISTA/SA�DE ', 'Unidade do SENAC'),
('UEP - PAULISTA/TUR.HOSPITALIDADE ', 'Unidade do SENAC'),
('UEP - PETROLINA/ARTES ', 'Unidade do SENAC'),
('UEP - PETROLINA/BELEZA ', 'Unidade do SENAC'),
('UEP - PETROLINA/COM�RCIO ', 'Unidade do SENAC'),
('UEP - PETROLINA/GER�NCIA ', 'Unidade do SENAC'),
('UEP - PETROLINA/GEST�O ', 'Unidade do SENAC'),
('UEP - PETROLINA/IDIOMAS ', 'Unidade do SENAC'),
('UEP - PETROLINA/IMAGEM PESSOAL ', 'Unidade do SENAC'),
('UEP - PETROLINA/INFORM�TICA ', 'Unidade do SENAC'),
('UEP - PETROLINA/LANCHONETE EMP.PEDAGOGICA ', 'Unidade do SENAC'),
('UEP - PETROLINA/MEDIOTEC ', 'Unidade do SENAC'),
('UEP - PETROLINA/MODA ', 'Unidade do SENAC'),
('UEP - PETROLINA/PRODU��O ALIMENT�CIA ', 'Unidade do SENAC'),
('UEP - PETROLINA/QUALIF PROF EDUCACIONAL ', 'Unidade do SENAC'),
('UEP - PETROLINA/SA�DE ', 'Unidade do SENAC'),
('UEP - PETROLINA/TUR.HOSPITALIDADE ', 'Unidade do SENAC'),
('UEP - RECIFE/APRENDIZAGEM/COM�RCIO ', 'Unidade do SENAC'),
('UEP - RECIFE/ARTES ', 'Unidade do SENAC'),
('UEP - RECIFE/BRASILAR/CHEFIA ', 'Unidade do SENAC'),
('UEP - RECIFE/BRASILAR/COM�RCIO ', 'Unidade do SENAC'),
('UEP - RECIFE/BRASILAR/GEST�O ', 'Unidade do SENAC'),
('UEP - RECIFE/COM�RCIO ', 'Unidade do SENAC'),
('UEP - RECIFE/COMUNICA��O ', 'Unidade do SENAC'),
('UEP - RECIFE/DESIGN ', 'Unidade do SENAC'),
('UEP - RECIFE/GER�NCIA ', 'Unidade do SENAC'),
('UEP - RECIFE/GEST�O ', 'Unidade do SENAC'),
('UEP - RECIFE/HOSPITALIDADE ', 'Unidade do SENAC'),
('UEP - RECIFE/PROJETO ', 'Unidade do SENAC'),
('UEP - RECIFE/SA�DE ', 'Unidade do SENAC'),
('UEP - RECIFE/SEGURAN�A ', 'Unidade do SENAC'),
('UEP - VIT�RIA/ARTES ', 'Unidade do SENAC'),
('UEP - VIT�RIA/COM�RCIO ', 'Unidade do SENAC'),
('UEP - VIT�RIA/GER�NCIA ', 'Unidade do SENAC'),
('UEP - VIT�RIA/GEST�O ', 'Unidade do SENAC'),
('UEP - VIT�RIA/IDIOMAS ', 'Unidade do SENAC'),
('UEP - VIT�RIA/IMAGEM PESSOAL ', 'Unidade do SENAC'),
('UEP - VIT�RIA/INFORM�TICA ', 'Unidade do SENAC'),
('UEP - VIT�RIA/SA�DE ', 'Unidade do SENAC'),
('UEP - VIT�RIA/TUR.HOSPITALIDADE ', 'Unidade do SENAC'),
('UEP RECIFE - CURSOS ', 'Unidade do SENAC'),
('UEP RECIFE - GER�NCIA ', 'Unidade do SENAC'),
('UHT - CURSOS ', 'Unidade do SENAC'),
('UHT - EMPRESA PEDAG�GICA ', 'Unidade do SENAC'),
('UHT - EVENTOS ', 'Unidade do SENAC'),
('UHT - GER�NCIA ', 'Unidade do SENAC'),
('UHT - HOSPITALIDADE ', 'Unidade do SENAC'),
('UHT - PROJETO ', 'Unidade do SENAC'),
('UHT - TURISMO ', 'Unidade do SENAC'),
('UIP - EMPRESA PEDAGOGICA ', 'Unidade do SENAC'),
('UIP - GER�NCIA DE IMAGEM PESSOAL ', 'Unidade do SENAC'),
('UIP - IMAGEM PESSOAL ', 'Unidade do SENAC'),
('UIP - PROJETO ', 'Unidade do SENAC'),
('UIP - SA�DE ', 'Unidade do SENAC'),
('UIS - CURSOS ', 'Unidade do SENAC'),
('UIS - GER�NCIA ', 'Unidade do SENAC'),
('UNIDADE DE PROJETOS ESTRATEGICOS ', 'Unidade do SENAC'),
('UTIC - CURSOS ', 'Unidade do SENAC'),
('UTIC - GERENCIA ', 'Unidade do SENAC'),
('UTV - CURSOS ', 'Unidade do SENAC'),
('UTV - GERENCIA ', 'Unidade do SENAC')

GO


